### ISSUE TITLE
Error code: 10 - BadAccess

### ISSUE THREAD

**Issue by pablopunk** [aesophor/Wmderland#1]
```bash
E1205 09:27:47.794860 12305 wm.cpp:372] Received X error:
    Request: 2    Error code: 10 - BadAccess (attempt to access private resource denied)
    Resource ID: 620
```

[![asciicast](https://asciinema.org/a/L12cgLilNsVGZ4RImfi4oRLkg.svg)](https://asciinema.org/a/L12cgLilNsVGZ4RImfi4oRLkg)

**Comment by pablopunk** [comment]
Forgot to say that the wm looks dope, congrats. I just wanna try it :grin:

**Comment by aesophor** [comment]
Hello,
1. I usually bring up my wm by typing `startx`. But before that, you should put `exec Wmderland` at the end of ~/.xinitrc (also make sure there's only one exec statement, don't invoke other wm!)
2. Please re-clone this repo, I've replaced the hardcoded SCREEN_WIDTH and SCREEN_HEIGHT with a flexible alternative way. (Sorry about that!)


Sorry for late reply! Please let me know if it helped! Thanks!

**Comment by aesophor** [comment]
At the end of my .xinitrc says `exec startkde`. That's because I'm running my wm with KDE.

**Comment by pablopunk** [comment]
hmm that was fast actually. I didn't modify my xinitrc, I'm using the default elementary OS desktop, will it work with that?

**Comment by pablopunk** [comment]
Maybe replacing `gala` by `Wmderland` in pantheon.session works

**Comment by aesophor** [comment]
> Maybe replacing `gala` by `Wmderland` in pantheon.session works

I found a related discussion [here on reddit](https://www.reddit.com/r/elementaryos/comments/1r5z49/elementary_os_with_i3_wm/)
