### ISSUE TITLE
add windowfocus-follows-mouse feature

### ISSUE THREAD

**Issue by Quoteme** [aesophor/wmderland#33]
just as the title says. There should be an equivalent to `focus_follows_mouse  (yes|no)` as in i3. So if you move the mouse from one window into another, the focus should switch to that window.
Default should be set to yes, because thats how it is in i3

**Comment by aesophor** [comment]
Hi there, this feature is now available in the staging branch! #34 

Currently it seems to be bug-free (what a bold statement lol), but I'll test it for a few days. If everything goes well, I'll merge it into master.

**Comment by aesophor** [comment]
@Quoteme @the-coffee-coder 

The `focus_follows_mouse` feature has been merged into master! :smile:
