### ISSUE TITLE
Wont run after login on sddm

### ISSUE THREAD

**Issue by mamahnxarya201** [aesophor/wmderland#38]
i installed wmderland via yay and copied the config file and xsession but after i select it and login via sddm nothing happen my screen just stuck on sddm

**Comment by aesophor** [comment]
Hi, sorry for late reply!

That's a bit weird... I just tested SDDM + wmderland on both Arch Linux and Linux Mint and they worked. Could you help me check the following:

1. The config file is placed at `~/.config/wmderland/config`
2. The .desktop file is placed at `/usr/share/xsessions/wmderland.desktop`
3. The output of `which wmderland` is "/usr/local/bin/wmderland"

Finally, if everything mentioned above is correct, can you check if there's a file `/tmp/wmderland.STACKTRACE`? If this file is found, please post its content. Thanks!

**Comment by mamahnxarya201** [comment]
iam sorry for my late reply but after trying with other wm (xmonad,i3wm,openbox) the sddm just hangs. I think this is a sddm bug going to try it on another display manager and for stacktrace i will send it soon i get to my computer

**Comment by aesophor** [comment]
> iam sorry for my late reply but after trying with other wm (xmonad,i3wm,openbox) the sddm just hangs. I think this is a sddm bug going to try it on another display manager and for stacktrace i will send it soon i get to my computer

No problem! Thank you so much for trying out this wm. If you have any feedback or issue, please let me know (although I might be late to reply since recently I have some critical stuff to deal with)

**Comment by mamahnxarya201** [comment]
There is no stacktrace in my machine i switch to ly but yep still no works so this is my machine issues not your wm

**Comment by aesophor** [comment]
> There is no stacktrace in my machine i switch to ly but yep still no works so this is my machine issues not your wm

Okay! Then I'll close this issue for now. If you need help with this wm, please let me know!
