### ISSUE TITLE
[Bug] Doesn't work on Fedora Workstation 31

### ISSUE THREAD

**Issue by cristianovitorino** [aesophor/wmderland#39]
#### Steps to reproduce 
1. Follow BUILD.md install instructions
2. Reboot
3. Try to login

#### Current behaviour (bug)

- Compiles normally, but no entry is linked to the session manager (tested on GDM and LightDM). The file itself (wmderland.desktop) is created and should behave normally, but simply does not.
- Some success with .xinitrc but you are greeted with a black screen. Example config is correctly in place.
- Tested on a standard Fedora Workstation install on a HDD and on a Virtual Machine, same behaviour on both test cases.

#### Expected behaviour (correct)
- A session entry should be linked to the session manager.
- Login should proceed normally and work with common session managers like GDM or LightDM, and not have a black screen in case of usage with .xinitrc.

#### Hardware and Driver

- **CPU:** Intel i5-3570K
- **GPU:** NVIDIA GeForce GTX 970
- **NVIDIA Driver Version:** 440.64

**Comment by aesophor** [comment]
> Expected behaviour (correct)
>
> * A session entry should be linked to the session manager.
> * Login should proceed normally and work with common session managers like GDM or LightDM, and not have a black screen in case of usage with .xinitrc.

Thank you very much for the detailed bug report!

For the first one, I'll update BUILD.md. `wmderland.desktop` has to be copied to `/usr/share/xsessions/`.

For the second one, a black screen should be correct, you just have to modify the config file to get wallpaper and [keybindings](https://github.com/aesophor/wmderland/blob/master/example/config#L167) to work. You can also try to launch [`rofi`](https://github.com/aesophor/wmderland/blob/master/example/config#L166). At the time being, I'm installing fedora workstation 31 on Virtualbox.

**Comment by cristianovitorino** [comment]
> > Expected behaviour (correct)
> > 
> > * A session entry should be linked to the session manager.
> > * Login should proceed normally and work with common session managers like GDM or LightDM, and not have a black screen in case of usage with .xinitrc.
> 
> Thank you very much for the detailed bug report!
> 
> For the first one, I'll update BUILD.md. `wmderland.desktop` has to be copied to `/usr/share/xsessions/`.
> 

Oh the file is created on `/usr/share/xsessions/`, that is not the problem, sorry for not explaining correctly, the problem is that it never shows on either GDM or LightDM. There is no way to login into wmderland other than the .xinitrc.

> For the second one, a black screen should be correct, you just have to modify the config file to get wallpaper and [keybindings](https://github.com/aesophor/wmderland/blob/master/example/config#L167) to work. You can also try to launch [`rofi`](https://github.com/aesophor/wmderland/blob/master/example/config#L166). At the time being, I'm installing fedora workstation 31 on Virtualbox.

OK, thank you. I'll try to see what I can do config wise to see if works, I'm used to i3-gaps, shouldn't be too hard, but using .xinitrc is a bummer for me, would be nice if it worked with GDM or LightDM.

I'm also testing on other distros on VM the moment, see if I can help track down the problem.

**Comment by aesophor** [comment]
I've [updated BUILD.md](https://github.com/aesophor/wmderland/blob/master/BUILD.md) (the instructions on how to modify the config file are also included).

I'm going to test it on LighDM and GDM! My fedora VM is ready

**Comment by cristianovitorino** [comment]
> I've [updated BUILD.md](https://github.com/aesophor/wmderland/blob/master/BUILD.md) (the instructions on how to modify the config file are also included).
> 
> I'm going to test it on LighDM and GDM! My fedora VM is ready

Thanks for looking into this.

I've followed the update BUILD.md, but wmderland still doesn't show up on GDM.

I managed to get wmderland working normally on VM, on EndeavourOS (Arch Linux under the hood) through the AUR package.

**Comment by aesophor** [comment]
It's a bit weird... I can successfully find wmderland's entry in GDM and execute wmderland.

I also slightly modified the config to display wallpaper and launch gnome-terminal via keybinds:
* replaced all occurrences of "urxvt" with "gnome-terminal"
* added this line: `exec feh --bg-fill ~/Pictures/Wallpaper.jpg`

![scrot-2020-03-08_101305_632x619](https://user-images.githubusercontent.com/32998585/76155446-f6790800-6126-11ea-9cdc-fe9734a1032b.png)
![scrot-2020-03-08_102351_834x1011](https://user-images.githubusercontent.com/32998585/76155449-f8db6200-6126-11ea-8faa-3eb6ed1c6bda.png)

**Comment by aesophor** [comment]
@cristianovitorino Could you maybe post the output of `ls -la /usr/share/xsessions` please? I'll also check on Google if there's any option of GDM that can possibly interfere with the desktop files in this directory.

**Comment by cristianovitorino** [comment]
Weird indeed. I have a standard vanilla Fedora. Also the Fedora installed fresh new on the VM has the same behaviour. I just can't comprehend what's happening. And yet, it works normally on EndeavourOS.

My ls:
![sábado-07-março-2020_23-31-46](https://user-images.githubusercontent.com/57003922/76155545-14fde580-60cc-11ea-95cf-d6ab89966fc3.png)

**Comment by aesophor** [comment]
> Weird indeed. I have a standard vanilla Fedora. Also the Fedora installed fresh new on the VM has the same behaviour. I just can't comprehend what's happening. And yet, it works normally on EndeavourOS.
> 
> My HDD Fedora ls:
> ![sábado-07-março-2020_23-31-46](https://user-images.githubusercontent.com/57003922/76155545-14fde580-60cc-11ea-95cf-d6ab89966fc3.png)

I've found the problem. The permission of `wmderland.desktop` must be set to readable by groups and others:
```
sudo chmod go+x /usr/share/xsessions/wmderland.desktop
```

**Comment by cristianovitorino** [comment]
> > Weird indeed. I have a standard vanilla Fedora. Also the Fedora installed fresh new on the VM has the same behaviour. I just can't comprehend what's happening. And yet, it works normally on EndeavourOS.
> > My HDD Fedora ls:
> > ![sábado-07-março-2020_23-31-46](https://user-images.githubusercontent.com/57003922/76155545-14fde580-60cc-11ea-95cf-d6ab89966fc3.png)
> 
> I've found the problem. The permission of `wmderland.desktop` must be set to readable by groups and others:
> 
> ```
> sudo chmod go+x /usr/share/xsessions/wmderland.desktop
> ```

I was about to test just that haha. Let me try it out.

**Comment by cristianovitorino** [comment]
Unfortunately still doesn't work. I'll try altering permissions to different groups, if that doesn't work I'll try to `dnf autoremove` GDM and reinstall it. It will break my GNOME setup a bit, but I'm really puzzled by this problem.

![IMG_20200307_234321701](https://user-images.githubusercontent.com/57003922/76155728-c140cb80-60ce-11ea-98d5-36a45085bd16.jpg)

**Comment by cristianovitorino** [comment]
No luck. Made a clean install of GDM but didn't solve the issue. Altering groups didn't help either.

**Comment by aesophor** [comment]
> No luck. Made a clean install of GDM but didn't solve the issue. Altering groups didn't help either.
> 
> I'm out of ideas.

This is really confusing lol... Does it also happen on a VM or only on the HDD install?

**Comment by aesophor** [comment]
What if we change `Exec=i3` to `Exec=wmderland` (and the same for TryExec)?

**Comment by cristianovitorino** [comment]
> This is really confusing lol... Does it also happen on a VM or only on the HDD install?

Same behaviour on a fresh install of Fedora on the VM. What gives right? LOL

BTW, I've installed another WM (`awesome`) just to see if it's a problem directly related to Fedora itself and it's GDM, but the `awesome` WM showed up normally.

I blame ghosts. Your WM is haunted dude haha.

**Comment by cristianovitorino** [comment]
> What if we modify **/usr/share/xsessions/i3.desktop** and change `Exec=i3` to `Exec=wmderland` (and the same for TryExec)?

Good idea, let me check.

**Comment by aesophor** [comment]
The screenshots I posted earlier was tested with `Fedora-Workstation-Live-x86_64-31-1.9.iso` (fresh install). I've updated `build.sh` and [now it will automatically install the .desktop file](https://github.com/aesophor/wmderland/blob/master/build.sh#L54). I'll try to reinstall fedora on a VM again.

I'm really sorry for causing you spending so much time debugging this issue...

**Comment by cristianovitorino** [comment]
> I'm really sorry for causing you spending so much time debugging this issue...

Hey man no problem at all, thanks for trying to help, saw your post on r/unixporn and really wanted to give it a go, since I love i3-gaps and minimalism : )

BTW:
> What if we modify /usr/share/xsessions/i3.desktop and change Exec=i3 to Exec=wmderland (and the same for TryExec)?

This worked!

What's up with that? I wonder WTH Fedora is doing under the hood for this bizarre behaviour to appear.

**Comment by aesophor** [comment]
> Hey man no problem at all, thanks for trying to help, saw your post on r/unixporn and really wanted to give it a go, since I love i3-gaps and minimalism : )

Thank you so much for trying it out! I'm so happy to read this!

> This worked!
> 
> What's up with that? I wonder WTH Fedora is doing under the hood for this bizarre behaviour to appear.

Great! I'm really clueless about this... May I ask you to `sudo cp i3.desktop wmderland.desktop` and see if the entry shows up in GDM?

**Comment by cristianovitorino** [comment]
> Great! I'm really clueless about this... May I ask you to `sudo cp i3.desktop wmderland.desktop` and see if the entry shows up in GDM? My VM is still installing

Doesn't work : (

**Comment by aesophor** [comment]
Tried reinstalling Fedora workstation 31 on Virtualbox and it works... so confusing

![scrot-2020-03-08_122149_305x357](https://user-images.githubusercontent.com/32998585/76156587-6becd480-6137-11ea-9da9-933083180c83.png)

![scrot-2020-03-08_122252_836x630](https://user-images.githubusercontent.com/32998585/76156596-98085580-6137-11ea-83ac-16590de6945c.png)

I'm using virtualbox 5.2.32 and I downloaded the .iso from: https://getfedora.org/en/workstation/download/
![scrot-2020-03-08_121108_580x204](https://user-images.githubusercontent.com/32998585/76156476-ea487700-6135-11ea-9a77-a03b82dc1963.png)

I'm out of ideas too...

**Comment by cristianovitorino** [comment]
Yeah, that's exactly how I always installed.

I deleted wmderland clean from my Fedora and reinstalled it again.

It... works now. But why? LOL It finally shows up on GDM.

I've already deleted it clean and reinstalled multiple times and never worked, but now it did? Did you change something on the source code in the last hour?

I have no idea why or how it works now.

Also shows up on CDM:
![domingo-08-março-2020_01-28-34](https://user-images.githubusercontent.com/57003922/76156777-cb1dfb00-60dd-11ea-93e4-3b6640417162.png)

**Comment by aesophor** [comment]
> Yeah, that's exactly how I always installed.
> 
> I deleted wmderland clean from my Fedora and reinstalled it again.
> 
> It... works now. But why? LOL It finally shows up on GDM.
> 
> I've already deleted it clean and reinstalled multiple times and never worked, but now it did? Did you change something on the source code in the last hour?

That's great!

I did add the following line to `build.sh` in the last hour. When running `build.sh --install`, it will ensure the desktop file's permission is set to 644, although I think this probably won't help as you've already manually set the permission to 644 before, and even tried making a copy from i3.desktop.
```
sudo install -D -m644 ../example/wmderland.desktop /usr/share/xsessions/
```

<br>

Perhaps reinstalling GDM really did clean something... I don't know either lol. But anyways, I'm so glad it is working now. If you have any other feature request or issue, please let me know! :smile_cat:

**Comment by cristianovitorino** [comment]
Thanks for the help man.

Could you add a recommendation on BUILD.md for Fedora users saying that you might need to reinstall GDM if wmderland doesn't show up on their GDM even after reboot? Also a warning that removing GDM with autoremove will break GNOME a bit, but they can restore it by just reinstalling the environment.

I think that's the best we can do for now to help if anyone else has the same issue.

The steps I did:
```
sudo systemctl disable gdm.service
sudo dnf autoremove -y gdm
sudo dnf upgrade -y
sudo dnf install -y gdm
sudo dnf group install -y gnome-desktop
```

**Comment by aesophor** [comment]
No problem! I'll add it right away.

**Comment by cristianovitorino** [comment]
> No problem! I'll add it right away.

Awesome! Thanks for everything. Gonna finally tinker with wmderland soon : )

**Comment by cristianovitorino** [comment]
Oh, just a last thing: a important step I think is to do a clean delete and clean recompile of wmderland **AFTER** reinstalling GDM and rebooting.

**Comment by aesophor** [comment]
Thank you! I've updated BUILD.md

https://github.com/aesophor/wmderland/blob/master/BUILD.md#gdm-entry-not-present-fedora-workstation-31
