### ISSUE TITLE
Focus on hover won't be re-enabled after clicking non-floating window

### ISSUE THREAD

**Issue by takagiy** [aesophor/wmderland#41]
## Expected Behavior
Window focusing should follow the mouse moving.

## Current Behavior
After clicking non-floating windows, the window focusing seems to remain being disabled.

## Steps to Reproduce
1. Open some non-floating windows.
2. Click the window while holding the Mod key.
3. Move the mouse cursor around over the windows.
    (Window focusing won't follow the mouse.)

## Environment
version: v1.0.4
dm: `sddm` v0.18.1

## Possibly Related Lines
https://github.com/aesophor/wmderland/blob/c3c5bc61796a2c9862d3fea915005e54cd9a332f/src/window_manager.cc#L419-L423

**Comment by aesophor** [comment]
Thank you so much! I'm gonna look into this problem tomorrow.

**Comment by aesophor** [comment]
Fixed in 77791fa6e3d391ef21cf98bd773d204cd52d38aa.
