### ISSUE TITLE
[feature] Drag and Drop window arrangement

### ISSUE THREAD

**Issue by takagiy** [aesophor/wmderland#43]
Hello!

Thanks a lot for your working! I really like this modern and clean window manager.
Sorry to make a notice out of the blue, but I'm now trying to write a patch for this WM that lets windows to be moved by Drag and Drop (with holding the modifier). That feature is originally implemented in the [Sway wm](https://github.com/swaywm/sway).
Here[\[open\]](https://imgur.com/gallery/weONU0e) is my work in progress screen recording of the patch. I'm very glad if you get interested in it.
I'm going to make a detailed explanation regarding it after a while by creating a pull request.

Thank you again.

**Comment by aesophor** [comment]
Wow this is amazing, I'm definitely looking forward to merging this!

Thank you very much for taking interest in this wm and adding new features to it, which keeps this project alive! I'm really grateful.
