### ISSUE TITLE
Initializing the cursor look

### ISSUE THREAD

**Issue by takagiy** [aesophor/wmderland#45]
I switched my display manager from sddm to ly.
After that, I had a problem in my desktop: The cursor looks strange to me, it was an X mark.
After the wm calls `Mouse::SetCursor()`, the cursor shape turns into the normal arrow shape.
[According to the archwiki](https://wiki.archlinux.org/index.php/Cursor_themes#Change_X_shaped_default_cursor), it happens because the wm doesn't initialize the cursor if my understanding is correct. However, I don't know why it doesn't occur while I was using sddm.
I edited the config referring the archwiki's article and the problem was fixed.
If this behavior is not intended, the wm may be able to initialize the cursor shape at the start to fix it.

## Expected Behavior

The mouse cursor always looks normal such as an arrow.

## Current Behavior

The mouse cursor looks an unfamiliar X shape if it is not on any windows.

## Steps to Reproduce
* Login to the desktop
* Open a window and move the cursor on the window.
* Move the cursor from the window to the background.

## Environment
version: 1.0.5
dm: `ly` 0.5.0

## Related Informations

[herbstluftwm's related implementation](https://github.com/herbstluftwm/herbstluftwm/blob/3f3e60a73536947984a52de20d4baec66b824660/src/mousemanager.cpp#L32-L34)

Thank you!

**Comment by takagiy** [comment]
Oops, I posted the draft by mistake. I'm Sorry.
Closing this temporarily.

**Comment by aesophor** [comment]
In 0e5122a9d446608b7d0760067377a6c6ee357e78, I added the `Mouse` class but forgot to initialize the cursor look to `CURSOR_NORMAL`.

Could you please confirm if it has been fixed in the latest commit?

**Comment by takagiy** [comment]
The latest `master` works fine.
Thank you for fixing.

**Comment by aesophor** [comment]
Thank you so much for your support!
If there's anything else, please let me know.
